**Introdução ao numpy**

In [1]:
import numpy as np

In [2]:
matriz = np.array([[1,2,3], [4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Tipos

In [3]:
type(matriz)

numpy.ndarray

In [4]:
matriz.dtype.name

'int64'

Dimensões do dataframe

In [5]:
matriz.shape

(2, 3)

In [6]:
matriz.size

6

Criando valores (passo a passo, espaçados ou randonicos)

In [7]:
np.arange(0, 30, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [9]:
np.random.randint(0, 30, 5)

array([13, 27, 28,  2, 25])

In [11]:
matriz2 = np.random.randint(0, 30, 6).reshape(3,2)
matriz2

array([[26,  1],
       [ 0,  0],
       [24,  4]])

Operações com Numpy

In [13]:
matriz.max()

6

In [15]:
# valor maximo
matriz.argmax()

5

In [17]:
# media
matriz.mean()

3.5

In [18]:
# desvio padrão
matriz.std()

1.707825127659933

In [24]:
matriz3 = np.array([[2,4,6], [8,7,1]])
matriz3

array([[2, 4, 6],
       [8, 7, 1]])

In [25]:
matriz3.shape

(2, 3)

In [27]:
matriz + matriz3

array([[ 3,  6,  9],
       [12, 12,  7]])

In [28]:
matriz * matriz3

array([[ 2,  8, 18],
       [32, 35,  6]])

In [29]:
matriz3**2

array([[ 4, 16, 36],
       [64, 49,  1]])

# Seleção e alteração de valores

In [30]:
matriz3

array([[2, 4, 6],
       [8, 7, 1]])

In [31]:
matriz3[1][1]

7

In [32]:
matriz3[0][2]

6

In [34]:
matriz3[matriz3 > 4]

array([6, 8, 7])

In [36]:
matriz3[1][matriz3[1] > 4]

array([8, 7])

In [38]:
matriz3[1][0] = 16
matriz3

array([[ 2,  4,  6],
       [16,  7,  1]])

In [40]:
matriz3 = np.insert(matriz3, 1, [0,0,1], axis=0)
matriz3

array([[ 2,  4,  6],
       [ 0,  0,  1],
       [ 0,  0,  1],
       [16,  7,  1]])

In [42]:
matriz3.shape

(4, 3)