# numpy coding

In [7]:
import numpy as np

In [8]:
NumP_Array = np.array([[1, 2, 3], [4, 6, 7]])
print(NumP_Array)


[[1 2 3]
 [4 6 7]]


In [9]:
NP1 = np.array([[1, 3], [4, 5]])
print(f"NP1: {NP1}")
NP2 = np.array([[3, 4], [5, 7]])
print(f"NP2: {NP2}")
# 1 3 | 3 4
# 4 5 | 5 7
# Multiply row - column 1*3 + 3*5
MNP = NP1@NP2
print(f"MNP NP1@NP2: {MNP}")

# Multiply row - column 1*3 + 3*5
MNP3 = np.dot(NP1, NP2)
print(f"MNP3 np.dot(NP1, NP2): {MNP3}")

# multiply row - row 1*3 | 3 * 4
MNP2 = NP1*NP2
print(f"MNP2 NP1*NP2: {MNP2}")

# multiply row - row 1*3 | 3 * 4
MNP4 = np.multiply(NP1, NP2)
print(f"MNP4 np.multiply(NP1, NP2): {MNP4}")


NP1: [[1 3]
 [4 5]]
NP2: [[3 4]
 [5 7]]
MNP NP1@NP2: [[18 25]
 [37 51]]
MNP3 np.dot(NP1, NP2): [[18 25]
 [37 51]]
MNP2 NP1*NP2: [[ 3 12]
 [20 35]]
MNP4 np.multiply(NP1, NP2): [[ 3 12]
 [20 35]]


In [10]:
# 1 3 | 3 4
# 4 5 | 5 7
# sum row 1 + 3 | 3 + 4
Sum1 = NP1 + NP2
print(f"Sum NP1 + NP2: {Sum1}")

# sub row 1 - 3 | 3 - 4
Sub1 = NP1 - NP2
print(f"Sub1 NP1 - NP2: {Sub1}")
Sub2 = np.subtract(NP1, NP2)
print(f"Sub2 np.subtract(NP1, NP2): {Sub2}")
# sum all elements array
El_Sum = np.sum(NP1)
print(f"El_Sum np.sum(NP1): {El_Sum}")

Broad_Nump = NP1 + 3
print(f"Broad_Nump: {Broad_Nump}")

NP3 = np.array([[3,4]])
print(f"np1+np3: {NP1 + NP3}")

Sum NP1 + NP2: [[ 4  7]
 [ 9 12]]
Sub1 NP1 - NP2: [[-2 -1]
 [-1 -2]]
Sub2 np.subtract(NP1, NP2): [[-2 -1]
 [-1 -2]]
El_Sum np.sum(NP1): 13
Broad_Nump: [[4 6]
 [7 8]]
np1+np3: [[4 7]
 [7 9]]


In [13]:
D = np.divide([12, 14, 16], 5)
print(f"np.divide([12, 14, 16], 5) = {D}")

D = np.floor_divide([12, 14, 16], 5)
print(f"D = {D}")

print(np.math.sqrt(10))

np.divide([12, 14, 16], 5) = [2.4 2.8 3.2]
D = [2 2 3]
3.1622776601683795


In [24]:
ND = np.random.standard_normal((3,4))
print("Normal distribution: ", ND)
print()
UD = np.random.uniform(1,12,(3,4))
print("UD: ", UD)
print()
print("rand: ", np.random.rand())
print()
Random_arr = np.random.randint(1, 50, (2,5))
print("randint: ", Random_arr)
print()

Normal distribution:  [[ 1.78110523 -0.19083346  0.47250494  0.8059946 ]
 [ 0.16091464 -0.06392602  1.54895613  2.00860277]
 [-0.76655829  1.3532093  -1.01763656  0.6353455 ]]

UD:  [[1.68476225 5.85120359 1.91805657 3.45917319]
 [4.3382014  4.45014941 4.08738986 7.71122825]
 [3.42587173 2.35073715 6.91700401 2.41655138]]

rand:  0.3546811365342848

randint:  [[27 35 42 38 28]
 [22 17 17 49 12]]



In [30]:
Ze = np.zeros((3,4))
print("Zeros: ", Ze)
print()
Ones = np.ones((3,4))
print("Ones: ",Ones)
print()

Filter_Ar = np.logical_and(Random_arr > 30, Random_arr < 50)
print(Random_arr)
print("logical_and: ", Filter_Ar)

F_Random_Ar = Random_arr[Filter_Ar]
print("Trues: ", F_Random_Ar)


Zeros:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[27 35 42 38 28]
 [22 17 17 49 12]]
logical_and:  [[False  True  True  True False]
 [False False False  True False]]
Trues:  [35 42 38 49]


In [39]:
Data_N = np.array([1,3,4,5,7,9])
print("Data_N: ", Data_N)
Mean_N = np.mean(Data_N)
print("Mean: ", Mean_N)
Median_N = np.median(Data_N)
print("Median: ", Median_N)
Var_N = np.var(Data_N)
print("Var_N: ", Var_N)
SD = np.std(Data_N)
print("Standar desviation: ", SD)


Data_N:  [1 3 4 5 7 9]
Mean:  4.833333333333333
Median:  4.5
Var_N:  6.805555555555556
Standar desviation:  2.608745973749755


In [43]:
NumP_Array = np.array([[1, 2, 3], [4, 6, 7]])
print(NumP_Array)
Var_Nump = np.var(NumP_Array, axis=1)
print(Var_Nump)
Var_Nump2 = np.var(NumP_Array, axis=0)
print(Var_Nump2)

[[1 2 3]
 [4 6 7]]
[0.66666667 1.55555556]
[2.25 4.   4.  ]
