In [3]:
import numpy as np

In [4]:
a = np.arange(0,5)
b = np.arange(5, 10)
print("Array 1","\n",a)
print("Array 2","\n",b)
print("vertical stacking:","\n", np.vstack((a,b)))
print("horizontal stacking:","\n", np.hstack((a,b)))

Array 1 
 [0 1 2 3 4]
Array 2 
 [5 6 7 8 9]
vertical stacking: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
horizontal stacking: 
 [0 1 2 3 4 5 6 7 8 9]
