In [1]:
import numpy as np

In [2]:
a = np.arange(10, 20, 2)
b = np.array([[2], [2]])
print("a: ", a)
print("b: ", b)
print("adding tow different size arrays: ","\n",a+b)
print("multiplying a ndarray and a number: ","\n",a * 2)

a:  [10 12 14 16 18]
b:  [[2]
 [2]]
adding tow different size arrays:  
 [[12 14 16 18 20]
 [12 14 16 18 20]]
multiplying a ndarray and a number:  
 [20 24 28 32 36]
