In [9]:
import numpy as np

# Mean, Median and Standard Deviation


In [7]:
a = np.arange(5, 15, 2)
print("Array ", a)
print(f"Mean {np.mean(a)}")
print(f"Standard deviation {np.std(a)}")
print(f"Median: {np.median(a)}")

Array  [ 5  7  9 11 13]
Mean 9.0
Standard deviation 2.8284271247461903
Median: 9.0


# min max value and their index


In [26]:
a = np.array([[1, 6], [4, 3]])
print(f"Array: {a}")
print(f"Min: {np.min(a, axis=0)}")
print(f"Max: {np.max(a, axis=0)}")


Array: [[1 6]
 [4 3]]
Min: [1 3]
Max: [4 6]


In [25]:
a = np.array([[1, 6, 5], [4, 3, 7]])
print(f"Array: {a}")
print(f"Arg Min: {np.argmin(a, axis=0)} ")
print(f"Arg Max: {np.argmax(a, axis=1)}")


Array: [[1 6 5]
 [4 3 7]]
Arg Min: [0 1 0] 
Arg Max: [1 2]


# The Sorting Operation

In [21]:
a = np.array([1, 4, 2, 5, 3, 6, 8, 7, 9])
print(f"Array before {a}")
print(f"quicksort: {np.sort(a, kind='quicksort')}")


Array before [1 4 2 5 3 6 8 7 9]
quicksort: [1 2 3 4 5 6 7 8 9]


In [24]:
a = np.array([[5, 6, 7, 4], [9, 2, 3, 7]])
print(f"Before: {a}")
print('Sort along column :','\n',np.sort(a, kind='mergresort',axis=1))

Before: [[5 6 7 4]
 [9 2 3 7]]
Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
